dist: xenial
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build
  - cargo build --features=show_nalgebra
  - cargo test --all-targets --all-features
  # run doc-tests, because --all-targets includes examples but not doc-tests
  - cargo test --doc --all-features
