[package]
name = "vega_lite_3"
version = "0.1.0-dev"
authors = ["David Bernard <david.bernard.31@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "rust api for vega-lite 3"
repository = "https://github.com/davidB/showata"
readme = "README.md"
#category = ["visualization"]
keywords = ["visualization", "plot", "vega"]

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0.39"
derive_builder = "0.7.2"
failure = "0.1.5"
showata = {version = "0.1.0-dev", optional = true, path = "../showata"}

[dev-dependencies]
csv = "1.0"
